
spring:
  datasource:
    name: iot_boss
    url: jdbc:mysql://localhost:3306/xpu_hrms?serverTimezone=UTC&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
server:
  servlet:
    context-path: /
  port: 8080
mybatis:
  mapper-locations: classpath:/mapperxml/*.xml